# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MessageVerify' do

   # Mob
   pod 'MOBFoundation_IDFA'
   # SMSSDK
   pod 'SMSSDK'

  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MessageVerify

  target 'MessageVerifyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MessageVerifyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
